site_name: GIG Cymru NHS Wales - Software development handbook
site_description: >
  GIG Cymru NHS Wales Software Development Handbook provides guidance on software development standards, practices, and tools to ensure high-quality software delivery.
site_url: https://geoff1900.github.io/
repo_url: https://github.com/Geoff1900/software-development-standards/
docs_dir: doc
edit_uri: edit/main/doc/
extra_css:
  - stylesheets/extra.css
theme:
  name: material
  custom_dir: doc/overrides
  static_templates:
    - 404.html
  logo: assets/logo.png
  favicon: assets/favicon.ico
  icon:
    repo: fontawesome/brands/github
  font:
    text: Rubik
  palette:
    scheme: custom
  features:
 #   - navigation.tabs
    - navigation.footer
 #   - content.action.edit
    - content.action.view
    - content.code.copy
copyright: >
  Copyright &copy; 2025 GIG Cymru - NHS Wales –
  <a href="#__consent">Change cookie settings</a>
extra:
  consent:
    title: Cookie consent
    description: >- 
      We use cookies to optimise site functionality and give you the best
      possible experience, recognise your repeated visits and preferences, as
      well as to measure the effectiveness of our site and whether
      users find what they're searching for. With your consent, you're helping
      us to make our site better.
    cookies:
      analytics:
        name: Simple Analytics
        checked: true
  analytics:
    provider: simple
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets:
      check_paths: true
plugins:
  - search
  - table-reader
  - awesome-nav
